feat(todo-18): create api route for fetching all tasks
syed-alif-sazim/todo-list-app-be pull request #1
Opened 2024-12-17 13:33 UTC by syed-alif-sazim

**Description of change**
An API route is created to fetch all tasks from the database

**Associated trello link**
https://trello.com/c/6R5vUWRE

2024-12-17 14:08 UTC, syed-alif-sazim commented on src/main.ts
get rid of comments

2024-12-19 00:08 UTC, nur-zaman-sazim commented on src/task/task.entity.ts
> +  is_completed!: boolean;
instead of making it a snake case
We can set the field name in property

2024-12-19 00:08 UTC, nur-zaman-sazim commented on src/task/task.service.ts
> +    return this.em.findAll(Task);
let's use the Repository here as it involves only one entity

2024-12-19 10:41 UTC, syed-alif-sazim commented on src/task/task.entity.ts
> +  is_completed!: boolean;
Noted.  I will do this from next time onwards. Can you overlook it for now? Because I wrote is_completed everywhere in the frontend

2024-12-20 08:43 UTC, mahir-mohsin-sazim requested changes

2024-12-20 08:43 UTC, mahir-mohsin-sazim commented on src/task/task.entity.ts
> +  is_completed!: boolean;
please change it in the FE as well.

2024-12-21 05:10 UTC, syed-alif-sazim commented on src/task/task.entity.ts
> +  is_completed!: boolean;
I resolved this in the last PR

2024-12-22 14:54 UTC, mahir-mohsin-sazim approved these changes

2024-12-24 16:16 UTC, nur-zaman-sazim approved these changes

2024-12-25 12:44 UTC, merged