feat(todo-13): create API route to add a task
syed-alif-sazim/todo-list-app-be pull request #2
Opened 2024-12-17 13:36 UTC by syed-alif-sazim

Description of change
An API route is created to add a task in the database

Associated trello link
https://trello.com/c/F8jOfYR3

2024-12-20 08:46 UTC, mahir-mohsin-sazim requested changes

2024-12-20 08:46 UTC, mahir-mohsin-sazim commented on src/task/task.controller.ts
> +  async create(@Body() newTaskObj: { description: string; isCompleted: boolean }) {
use DTOs to validate payload in the backend.

2024-12-20 08:46 UTC, mahir-mohsin-sazim commented on src/task/task.service.ts
> +  async createTask(newTaskObj: { description: string; isCompleted: boolean }): Promise<Task> {
same here

2024-12-21 05:10 UTC, syed-alif-sazim commented on src/task/task.controller.ts
> +  async create(@Body() newTaskObj: { description: string; isCompleted: boolean }) {
I resolved this in the last PR

2024-12-21 05:10 UTC, syed-alif-sazim commented on src/task/task.service.ts
> +  async createTask(newTaskObj: { description: string; isCompleted: boolean }): Promise<Task> {
I resolved this in the last PR

2024-12-22 14:59 UTC, mahir-mohsin-sazim approved these changes

2024-12-24 16:22 UTC, nur-zaman-sazim approved these changes

2024-12-25 12:43 UTC, merged