feat(todo-14): create API route to edit task
syed-alif-sazim/todo-list-app-be pull request #4
Opened 2024-12-17 13:40 UTC by syed-alif-sazim

**Description of change**
An API route is created to edit a task and update it in the database

**Associated trello link**
https://trello.com/c/HwZPlpYo

2024-12-20 08:49 UTC, mahir-mohsin-sazim requested changes

2024-12-20 08:49 UTC, mahir-mohsin-sazim commented on src/task/task.controller.ts
> +  async updateTask(@Param('id') id: number, @Body('description') description: string) {
use DTOs for the payload validation

2024-12-20 08:49 UTC, mahir-mohsin-sazim commented on src/task/task.service.ts
> +      throw new Error('Task not found');
use NestJS built in `Exception handlers` please

2024-12-21 05:09 UTC, syed-alif-sazim commented on src/task/task.controller.ts
> +  async updateTask(@Param('id') id: number, @Body('description') description: string) {
I resolved this in the last PR

2024-12-21 05:09 UTC, syed-alif-sazim commented on src/task/task.service.ts
> +      throw new Error('Task not found');
I resolved this in the last PR

2024-12-22 14:58 UTC, mahir-mohsin-sazim approved these changes

2024-12-24 16:19 UTC, nur-zaman-sazim approved these changes

2024-12-25 12:43 UTC, merged