feat(todo-16): Create API route to toggle completion
syed-alif-sazim/todo-list-app-be pull request #5
Opened 2024-12-17 13:44 UTC by syed-alif-sazim

**Description of change**
An API route is created to change the completion status of a task in the database

**Associated trello link**
https://trello.com/c/BmL8RSg7

2024-12-20 08:51 UTC, mahir-mohsin-sazim requested changes

2024-12-20 08:51 UTC, mahir-mohsin-sazim commented on src/task/task.service.ts
> +      throw new Error('Task not found');
use NestJS built in `Exception Handlers` please

2024-12-20 08:51 UTC, mahir-mohsin-sazim commented on src/task/task.service.ts
> +    task.is_completed = !task.is_completed;
snake case in TS? please fix it

2024-12-22 14:58 UTC, mahir-mohsin-sazim approved these changes

2024-12-24 16:17 UTC, nur-zaman-sazim approved these changes

2024-12-25 12:42 UTC, merged